run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - deadcode
    - unused
    - gosimple
    - structcheck
    - varcheck
    - typecheck
    - ineffassign
    - gocyclo
    - gofmt

issues:
  exclude-rules:
    # Exclude linters with specific patterns
    - linters:
        - gofmt
      text: "is not gofmted with -s"