name: Go CI

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1