name: Go CI

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t retr0man99/go-app:latest .
        docker push retr0man99/go-app:latest
    
    - name: Trigger Deployment if successful
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: deployment
          client-payload: '{"component": "go-app"}'