name: Go CI Workflow

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Install dependencies
      run: go mod tidy

    - name: Run Unit Tests
      run: go test ./...

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run Linter
      run: golangci-lint run --config .golangci.yml